import type { Metadata } from "next";
import { Instrument_Serif, DM_Sans } from "next/font/google";
import "./globals.css";
import "ldrs/react/Squircle.css";

import ProgessProvider from "@/components/providers/progess-provider";
import Navbar from "@/components/common/navbar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import TanstackQueryProvider from "@/components/providers/tanstack-query-provider";
import { Toaster } from "@/components/ui/sonner";

const serif = Instrument_Serif({
  variable: "--font-serif",
  weight: ["400"],
  style: ["normal", "italic"],
});

const sans = DM_Sans({
  variable: "--font-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "rvyu.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${serif.variable} ${sans.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TanstackQueryProvider>
            <ProgessProvider>
              <Navbar />
              {children}
              <Toaster />
            </ProgessProvider>
          </TanstackQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
